export const products = [
    {
        description: 'Bottles of water',
        quantity: 50,
        price: 0.25,
        discount: 0,
        vat: 8, 
        total: 0,
    },
    {
        description: 'Chips',
        quantity: 38,
        price: 2.40,
        discount: 0,
        vat: 8, 
        total: 0,
    },
    {
        description: 'Coca Cola',
        quantity: 50,
        price: 0.50,
        discount: 0.10,
        vat: 8, 
        total: 0,
    },
    {
        description: 'Chocolate Bars',
        quantity: 50,
        price: 0.50,
        discount: 0.10,
        vat: 8, 
        total: 0,
    },
    {
        description: 'Hand Soup',
        quantity: 50,
        price: 0.50,
        discount: 0.10,
        vat: 8, 
        total: 0,
    },
    {
        description: 'Fish Meat',
        quantity: 9,
        price: 8.30,
        discount: 0,
        vat: 8.30, 
        total: 0,
    },
    {
        description: 'Humus',
        quantity: 4,
        price: 2.66,
        discount: 0,
        vat: 18, 
        total: 0,
    },
    {
        description: 'Banana Kg',
        quantity: 1,
        price: 1.25,
        discount: 0,
        vat: 22, 
        total: 0,
    },
];